const COUNTRY_CONTINENT = {
  Portugal: "Europa",
  Espanha: "Europa",
  França: "Europa",
  Itália: "Europa",
  Alemanha: "Europa",
  "Reino Unido": "Europa",
  Holanda: "Europa",
  Bélgica: "Europa",
  Suíça: "Europa",
  Grécia: "Europa",
  Polónia: "Europa",
  Irlanda: "Europa",
  Áustria: "Europa",
  Suécia: "Europa",
  Noruega: "Europa",
  Dinamarca: "Europa",
  Finlândia: "Europa",
  "República Checa": "Europa",
  Hungria: "Europa",
  Roménia: "Europa",
  Croácia: "Europa",
  Brasil: "América do Sul",
  Argentina: "América do Sul",
  Chile: "América do Sul",
  Peru: "América do Sul",
  Colômbia: "América do Sul",
  Uruguai: "América do Sul",
  México: "América do Norte",
  "Estados Unidos": "América do Norte",
  Canadá: "América do Norte",
  Cuba: "América do Norte",
  Marrocos: "África",
  Egito: "África",
  "África do Sul": "África",
  Quénia: "África",
  Tunísia: "África",
  Japão: "Ásia",
  China: "Ásia",
  Índia: "Ásia",
  Tailândia: "Ásia",
  Vietname: "Ásia",
  "Coreia do Sul": "Ásia",
  Indonésia: "Ásia",
  Turquia: "Ásia",
  Israel: "Ásia",
  "Emirados Árabes Unidos": "Ásia",
  Austrália: "Oceânia",
  "Nova Zelândia": "Oceânia",
};

function getContinent(country) {
  return COUNTRY_CONTINENT[country] || "Outro";
}

module.exports = { getContinent, COUNTRY_CONTINENT };
